// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EFCoreDemo.Models;

public partial class CourseDto
{
    public int CourseId { get; set; }

    public string Title { get; set; }

    public int Credits { get; set; }

    public int DepartmentId { get; set; }

    public string DepartmentName { get; set; }

    public DateTime DateModified { get; set; }

    public DateTime DateCreated { get; set; }
}