// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace EFCoreDemo.Models;

public partial class CourseCreateDto : IValidatableObject
{
    [Required(ErrorMessage = "請填寫課程名稱")]
    [StringLength(50, ErrorMessage = "課程名稱長度不可超過 50 個字元")]
    [MinLength(3, ErrorMessage = "課程名稱長度不可小於 3 個字元")]
    public string Title { get; set; }

    [Range(1, 5, ErrorMessage = "設定課程評價需介於 1 ~ 5 之間")]
    public int Credits { get; set; } = 1;

    public int DepartmentId { get; set; }

    public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
    {
        if (this.Title.Contains("ASP.NET") && this.Credits < 5)
        {
            yield return new ValidationResult("ASP.NET 課程的評價必須大於等於 5", new[] { nameof(Credits) });
        }
    }
}