// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EFCoreDemo.Models;

public partial class CourseCreateDto
{
    public string Title { get; set; }

    public int Credits { get; set; } = 1;

    public int DepartmentId { get; set; }
}