// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace EFCoreDemo.Models;

public partial class ContosoUniversityContext : DbContext
{
    public override Task<int> SaveChangesAsync(CancellationToken cancellationToken = default)
    {
        var entries = ChangeTracker.Entries();

        foreach (var entry in entries)
        {
            switch (entry.State)
            {
                case EntityState.Added:
                    entry.CurrentValues.SetValues(new { DateCreated = DateTime.Now });
                    entry.CurrentValues.SetValues(new { DateModified = DateTime.Now });
                    break;

                case EntityState.Modified:
                    entry.CurrentValues.SetValues(new { DateModified = DateTime.Now });
                    break;
            }
        }

        return base.SaveChangesAsync(cancellationToken);
    }
}